version: '3.8'
services:
  database:
    image: postgres:15.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - './postgres:/var/lib/postgresql/data'
